name: Publish & Build

on: push

env:
  ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.mavenUsername }}
  ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.mavenPassword }}
  skip-integration-testing: true

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check APIs
        uses: gradle/gradle-build-action@v1
        with:
          distributions-cache-enabled: true
          configuration-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: |
            --stacktrace --scan \
              spotlessCheck \
              assemble \
              apiCheck

      - name: Clean project
        uses: gradle/gradle-build-action@v1
        with:
          arguments: clean

  publish-snapshot:
    if: "!startsWith(github.event.head_commit.message, 'Release')"
    name: Publishing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Publish publications
        uses: gradle/gradle-build-action@v1
        with:
          # Publish all projects
          arguments: publish --stacktrace

  publish-release:
    if: "startsWith(github.event.head_commit.message, 'Release')"
    name: Publishing
    runs-on: ubuntu-latest
    env:
      release-publications: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Publish publications
        uses: gradle/gradle-build-action@v1
        with:
          # Publish all projects
          arguments: |
            --stacktrace \
              publishPlugins \
              publish \
              closeAndReleaseSonatypeRepository

  gradle-sync:
    needs: [publish-snapshot, publish-release]
    runs-on: ubuntu-latest
    env:
      # Build test published artifacts
      use-non-local-version: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle sync
        uses: gradle/gradle-build-action@v1
        with:
          distributions-cache-enabled: true
          configuration-cache-enabled: false
          dependencies-cache-enabled: false
