name: Gradle wrapper update

on:
  schedule:
    - cron: '5 20 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      USE_NON_LOCAL_VERSION: true

    steps:
      - uses: actions/checkout@v2
        
      - name: Update gradle wrapper version
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: versions, gradle-wrapper
          reviewers: RinOrz

      - name: Run new gradle wrapper
        uses: gradle/gradle-build-action@v1
        with:
          gradle-version: wrapper
