name: Refresh versions

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Synchronizing dependencies
      uses: gradle/gradle-build-action@v1
      with:
        gradle-version: release-candidate
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        # Run https://github.com/jmfayard/refreshVersions
        arguments: refreshVersions

    - name: Commit the versions.properties file
      shell: bash
      run: |
        git config --local user.email "91298650+refresh-versions-bot@users.noreply.github.com"
        git config --local user.name "refresh-versions[bot]"
        git commit -m 'Refresh `versions.properties`' -a

    - name: Push the versions.properties file
      uses: ad-m/github-push-action@master
