name: Sync prebuilt dependencies

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 3 * * *'
  push:
    paths:
      - '.github/workflows/sync-dependencies.yml'
      # Also run this workflow whenever we update prebuilt configuration file
      - '**/prebuilt/build.gradle.kts'
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Synchronizing dependencies
      uses: gradle/gradle-build-action@v1
      with:
        gradle-version: release-candidate
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        # Run https://github.com/meowool-toolkit/gradle-toolkit/blob/main/dependency/prebuilt/build.gradle.kts#L44
        arguments: syncDependencies
      
    - name: Commit the synchronized dependencies file
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Sync prebuilt dependencies" -a

    - name: Push the synchronized dependencies file
      uses: ad-m/github-push-action@master
