name: Sync prebuilt dependencies

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 3 * * *'
  push:
    # Also run this workflow whenever we update prebuilt configuration file
    paths:
      - '**/prebuilt/build.gradle.kts'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Cache gradle wrapper
      uses: burrunan/gradle-cache-action@v1
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Synchronizing dependencies
      # Run https://github.com/meowool-toolkit/gradle-toolkit/blob/main/dependency/prebuilt/build.gradle.kts#L44
      run: ./gradlew syncDependencies
      
    - name: Commit the synchronized dependencies file
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Sync prebuilt dependencies" -a

    - name: Push the synchronized dependencies file
      uses: ad-m/github-push-action@master
